sudo: required
services:
    - docker
before_install:
  - docker build -t s3test-website-test -f Dockerfile.test .
script:
  - docker run -e CI=true s3test-website-test
deploy:
  provider: script
  script: bash ./scripts/deploy.sh
  on:
    branch: main