sudo: required

services:
    - docker
before_install:
  - docker build -t s3test-website-test -f Dockerfile.test .
script:
  - docker run s3test-website-test

before_deploy:
  - docker build -tag s3test-website-deploy .

deploy:
  provider: script
  script: bash ./scripts/deploy.sh
  on:
    branch: main